version: "3.8"

services:
  frontend:
    build:
      context: ./conf-connect-hub-main
    ports:
      - "8081:8080"
    volumes:
      - ./conf-connect-hub-main:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:123456789@db/virtual_conference_db1
    networks:
      - app_network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: virtual_conference_db1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
